stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: ubuntu:latest
  script:
    - pip install -r requirements.txt
    - jupyter-book clean docs
    - jupyter-book build docs
  artifacts:
    paths:
      - docs/_build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
